Feat/week xml04
NOW-SOPT-ANDROID/jeonghyun-yu pull request #11
Opened 2024-05-03 13:48 UTC by OliviaYJH

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #9 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 회원가입 구현하기
- 로그인 구현하기
- 내 정보 구현하기

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/NOW-SOPT-ANDROID/jeonghyun-yu/assets/81751105/302e2c2e-b826-4f5c-97c4-b18db2b38071

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴

2024-05-05 09:54 UTC, Larry7939 approved these changes
안녕하세요. 리뷰어를 맡게 된 Android 파트 31기 박지훈입니다 😀
우선순위에 따라 (P1 > P2 > P3) 리뷰를 남겼으니 참고해주시면 감사하겠습니다.
고생 많으셨습니다~

[정현님을 위한 유용한 코드 정리 팁 🎈]
Ctrl + Alt + L -> 개행 및 여백 정리
Ctrl + Alt + O -> 미사용 import 정리

[item_my_profile.xml의 tv_description이 길어지면 이름과 우측 화살표를 침범하는 현상]
힌트: contraint와 width를 조정해보시길 바랍니다.😊
| Before | After |
| :---: | :---: |
| ![image](https://github.com/NOW-SOPT-ANDROID/jeonghyun-yu/assets/70442964/9c3ea7b9-f81f-4dc7-ae4b-6823a591893a) | ![image](https://github.com/NOW-SOPT-ANDROID/jeonghyun-yu/assets/70442964/fb586244-1097-47ae-8f1d-4f5d093afaf3) |

2024-05-05 09:54 UTC, Larry7939 commented on app/src/main/java/com/sopt/now/datasource/InfoService.kt
> +        @Header("memberId") memberId: String
[P2]
재사용 될 가능성이 높은 memberId 헤더 같은 경우는 Interceptor로 처리해주는 것도 좋을 것 같아요!

2024-05-05 09:54 UTC, Larry7939 commented on app/src/main/java/com/sopt/now/presentation/auth/login/LoginActivity.kt
> +}
[P3]
Context의 유틸 확장함수로 만들어서 사용해도 좋을 것 같습니다.

```suggestion
Context.showToast(message: String) {
        Toast.makeText(this, message, Toast.LENGTH_SHORT).show()
}
```

2024-05-05 09:54 UTC, Larry7939 commented on app/src/main/java/com/sopt/now/presentation/auth/login/LoginViewModel.kt
> +                memberId = it.headers()["location"]
[P1]
memberId는 사용자 식별 값이라는 중요한 역할을 맡은 만큼, 
로컬 내 저장소에 저장해두면 향후 유지보수에 유용하게 사용할 수 있을 것 같아요!
ex) 
1. 앱 종료 후 재실행 시, memberId의 존재 유무에 따른 자동 로그인
2. memberId 헤더를 필요로 하는 API 호출
3. 뷰 랜딩 시마다 intent 혹은 argument로 memberId를 전달할 필요가 없게 됩니다.

로컬 내 저장소는 [SharedPreferences](https://developer.android.com/training/data-storage/shared-preferences?hl=ko)를 사용해보시는 것을 추천드립니다.

2024-05-05 09:54 UTC, Larry7939 commented on app/src/main/java/com/sopt/now/presentation/auth/signup/SignupActivity.kt
> +    }
[P1]
각 조건에 따라 다른 경고 메시지를 노출시켜줄 수 있도록 함수를 분리하는 것이 좋을 것 같아요!
예를 들어 패스워드로 "12345678" 입력 시, 길이 조건을 만족했음에도 "비밀번호는 8자 이상 12자 이하로 입력해주세요." 메시지가 노출되고 있습니다.

```
	    private fun containsDigit(password: String) {
	        if (!password.any { it.isDigit() }) {
                       showToast("비밀번호는 적어도 하나의 숫자를 포함해야 합니다.")
                 }
	    }
	
	    private fun containsAlphabet(password: String) {
                if (!password.any { it.isLetter() }) {
                       showToast("비밀번호는 적어도 하나의 알파벳을 포함해야 합니다.")
                }
	    }
	
	    private fun containsSpecialCharacter(password: String) {
	        val regex = Regex("[^a-zA-Z0-9]")
	        if (!password.any { it.toString().matches(regex) }) {
                        showToast("비밀번호는 적어도 하나의 특수 문자를 포함해야 합니다.")
                }
	    }
	
	    private fun isLengthValid(password: String) {
	        if (!password.length in 8..12) {
                         showToast("비밀번호는 8글자 이상 12글자 이내로 작성해주세요")
                }
	    }
	}
```

2024-05-05 09:54 UTC, Larry7939 commented on app/src/main/java/com/sopt/now/utils/BaseResponse.kt
> +}
[P3]
BaseResponse에 제네릭 타입의 data 변수를 추가해서,
다른 Response 클래스를 정의할 때 중복되는 코드(code, message)를 방지하는 것은 어떨까요?😊

```suggestion
@Serializable
data class BaseResponse<T> {
    @SerialName("code")
    val code: String? = null
    @SerialName("message")
    val message: String? = null
    @SerialName("data")
    val data: T? = null
}
```

Before
```
@Serializable
data class ResponseGetInfoDto(
    @SerialName("code")
    val code: Int,

    @SerialName("message")
    val message: String,

    @SerialName("data")
    val data: UserInfo
)

```

```
interface InfoService {
    @GET("member/info")
    suspend fun getUserInfo(
        @Header("memberId") memberId: String
    ): Response<ResponseGetInfoDto>
}
```

After

```
interface InfoService {
    @GET("member/info")
    suspend fun getUserInfo(
        @Header("memberId") memberId: String
    ): Response<BaseResponse<UserInfo>>
}
```

+ ResponseSignUpDto와 같이 code와 message로만 이루어진 Response는 BaseResponse로 대체할 수 있을 것 같습니다.😊

2024-05-05 09:54 UTC, Larry7939 commented on app/src/main/java/com/sopt/now/presentation/auth/signup/SignUpViewModel.kt
> +        viewModelScope.launch(Dispatchers.IO) {
Dispatcher 전달 좋습니다 😀😀

2024-05-05 09:54 UTC, Larry7939 commented on app/src/main/java/com/sopt/now/utils/ApiFactory.kt
> +    val retrofit: Retrofit by lazy {
lazy로 잘 선언해주셨군요 👍👍

2024-05-05 09:54 UTC, Larry7939 commented on app/src/main/java/com/sopt/now/presentation/main/mypage/MyPageFragment.kt
>          _binding = null
꼼꼼한 리소스 해제 좋습니다~~ 🤩🤩

2024-05-05 09:54 UTC, Larry7939 commented on app/src/main/java/com/sopt/now/presentation/main/mypage/MyPageFragment.kt
> +        myPageViewModel.userInfo.observe(viewLifecycleOwner) {
observe의 인자로 viewLifecycleOwner를 잘 넣어주셨군요~ 좋습니다 😁😁

2024-05-05 12:27 UTC, chanubc requested changes
아니 왜 이렇게 잘하시죠? 보면서 깜짝 놀랐네요
쉽게 쉽게 진짜 잘 짜시는 것 같습니다.
error hanling하는 코드는 제가 배웠네요

추가로 "!!" 과 "?" null 타입이 코드 전반적으로 반복되는데 반드시 필요한가 생각해보시면 좋을것 같습니다!
예상치 못한 null들은 여러 side effect를 불러올 수 있기 때문에 꼭 null로 지정 해야하는지 한번 고민해보시기 바랍니다!

2024-05-05 12:27 UTC, chanubc commented on app/build.gradle
> +    kapt "com.google.dagger:hilt-compiler:2.48.1"
추후 활용하실 계획인가요?? 대단합니다!

2024-05-05 12:27 UTC, chanubc commented on app/src/main/java/com/sopt/now/datasource/AuthService.kt
> +
코루틴 사용 좋네요!
아마 다음주에 배울건데 미리 하셨네용

2024-05-05 12:27 UTC, chanubc commented on app/src/main/java/com/sopt/now/datasource/AuthService.kt
> +    @POST("member/login")
추가로 반복되는 url주소들(member)은 상수화 해두면 좋습니다!
저 같은 경우 따로 object를 만들었어요
이건 취향 차이 입니다.

2024-05-05 12:27 UTC, chanubc commented on app/src/main/java/com/sopt/now/model/login/ResponseLoginDto.kt
> +)
반복되는 dto들은 BaseResponse로 따로 만드는 방법도 있습니다!
```kotlin
@Serializable
data class BaseResponse<T>(
    @SerialName("code")
    val code: Int,
    @SerialName("message")
    val message: String,
    @SerialName("data")
    val data: T? = null
)
```
이런식으로요!

2024-05-05 12:27 UTC, chanubc commented on app/src/main/java/com/sopt/now/model/login/ResponseLoginDto.kt
> +)
```kotlin
    @POST("$MEMBER/$LOGIN")
    suspend fun login(
        @Body request: RequestLoginDto
    ): Response<BaseResponse<Unit>>
```
로그인의 경우 전 이런식으로 사용했습니다!

2024-05-05 12:27 UTC, chanubc commented on app/src/main/java/com/sopt/now/presentation/auth/login/LoginActivity.kt
> +    }
scope함수의 사용을 정확하게 알고 쓰는 것도 좋을 것 같아요!

apply의 경우 초기화를 담당하는데 putExtra함수를 사용하는 것은 적합하지만 함수 본문을 실행하는 startActivity와 finish에서의 사용은 적합하지 않다 생각합니다! 객체 초기화를 한 후 객체 자신(this)를 반환하기 때문에 객체에 여러 설정을 적용할 때 적합하다 합니다.

also의 경우 객체의 초기화 또는 설정을 수행한 후, 해당 객체에 대한 추가 작업을 수행하고자 할때 사용합니다. also는 호출된 객체(it을 통해 접근)를 그대로 반환하기 때문에, 객체의 초기화나 설정 이후에 연쇄적인 작업을 할 때 유용하게 사용된다고 합니다!

```suggestion
    private fun navigateToMain(userId: String?) {
        Intent(this, MainActivity::class.java).apply {
           putExtra(MEMBER_ID, userId)
        }.also {
           startActivity(it)
        }
        finish()
    }
```
혹은
```kotlin
private fun navigateToMain(userId: String?) {
    val intent = Intent(this, MainActivity::class.java).apply {
        putExtra(MEMBER_ID, userId)
    }
    startActivity(intent)
    finish()
}
```

2024-05-05 12:27 UTC, chanubc commented on app/src/main/java/com/sopt/now/presentation/auth/login/LoginViewModel.kt
> +    var status: MutableLiveData<Boolean> = _status
```suggestion
    private val _status = MutableLiveData<Boolean>()
    val status: LiveData<Boolean> get()= _status
```
1. 우선 var + Mutable의 경우 가변 + 가변이라 사용하지 않는 것이 좋습니다!

2. 또 backing property에 있어 기존에  사용하던 방식( = _status )은 객체에 대한 참조를 가지고 있습니다. 따라서 status.value = “ “와 같이 내부 상태를 변경할 수 있게 됩니다.   
  
  제안드리는 두번째 방식의 경우
 _status 에 대한 참조를 매번 새롭게 얻는 방식입니다. 따라서 status를 통해 _status의 값을 변경할 수 없습니다. get()매서드가 LiveData 타입을 반환하기 때문이죠!

2024-05-05 12:27 UTC, chanubc commented on app/src/main/java/com/sopt/now/presentation/auth/login/LoginViewModel.kt
> +    fun getErrorMessage() = errorMessage
요런 것들도 추후에 Uistate를 활용하게 된다면 더욱 효율적일 거에요!

Uistate와 별개로
```suggestion
    private var _memberId: String? = null
    val memberId:String? get() = _memberId

    private var _errorMessage: String? = null
    val getErrorMessage:String? get() = _errorMessage
```

이렇게 사용해도 됩니다!

2024-05-05 12:27 UTC, chanubc commented on app/src/main/java/com/sopt/now/presentation/auth/login/LoginViewModel.kt
> +                    _status.postValue(true)
postValue활용 좋네요!!

2024-05-05 12:27 UTC, chanubc commented on app/src/main/java/com/sopt/now/utils/NetworkUtil.kt
> +}
폼 미쳤네요 ㄷㄷ

2024-05-05 12:27 UTC, chanubc commented on app/src/main/java/com/sopt/now/presentation/auth/login/LoginViewModel.kt
> +                }
!! 타입은 최대한 지양해주세요

2024-05-05 12:27 UTC, chanubc commented on app/src/main/java/com/sopt/now/presentation/auth/signup/SignupActivity.kt
> +        showToast((R.string.success_signup).toString())
```suggestion
        showToast(getString(R.string.success_signup))
```

2024-05-05 12:27 UTC, chanubc commented on app/src/main/java/com/sopt/now/presentation/auth/signup/SignupActivity.kt
> +                showToast(signUpViewModel.getErrorMessage()!!)
```suggestion
                showToast(signUpViewModel.getErrorMessage()?:"알 수 없는 오류..")
```

!!타입은 최대한 피하는게 좋습니다! 여기선 이런식으로 바꾸어도 되는데 getErrorMessgae함수에서 null인 경우에대한 핸들링은 먼저 하는게 더 나을 수 도있을 것 같아요.

2024-05-05 12:27 UTC, chanubc commented on app/src/main/java/com/sopt/now/presentation/main/mypage/MyPageViewModel.kt
> +                    userInfo = it.body()?.data!!
!! 는 지양해주세요
userInfo에 대한 null처리를 먼저 한 다음 값을 할당하면 될것 같습니다!

2024-05-05 12:27 UTC, chanubc commented on app/src/main/java/com/sopt/now/utils/ApiFactory.kt
> +}
```suggestion
object ServicePool {
    val authService: AuthService by lazy { create<AuthService>() }
    val loginService: AuthService by lazy { create<AuthService>() }
    val infoService: InfoService by lazy { create<InfoService>() }
}
```

이러면 서비스 중 하나만 사용되어도 ServicePool 객체가 참조될 때 나머지 서비스들도 모두 초기화되는 문제가 있습니다! 불필요한 리소스를 유발 할 것 같아요.

특히 네트워크 관련 서비스의 경우 초기화 과정에서 추가적인 시간이 소요될 수 있으므로 비효율적 일 수도 있을 것 같습니다!

2024-05-05 12:53 UTC, chanubc commented on app/src/main/java/com/sopt/now/model/login/ResponseLoginDto.kt
> +)
앗 위에서 적어주셧네용

2024-05-05 13:49 UTC, hyoeunjoo approved these changes
항상 멋진 정현언니~~!!! >_<

2024-05-05 13:49 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/presentation/auth/login/LoginActivity.kt
> +
짧은 내용들은 따로 함수로 안 빼서 작성했었는데 이렇게 따로 쓰니까 훨씬 위에서 보기 좋은 것 같아요

2024-05-05 13:49 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/presentation/main/MainActivity.kt
> +                            putString(MEMBER_ID, memberId)
ㅎㅎ 저도 UserId 얼른 빼겠습니다 자주 쓰는 값이니까요!!

2024-05-05 13:49 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/utils/ApiFactory.kt
> +
매번 신기한거 많이 보고 가네요.. 찾아보니 HTTP 클라이언트 라이브러리 중 하나로 OkHttpClient라는게 있군요!! 저렇게 클라이언트와 서버 사이의 시간을 정해두면 연결이 실패되었을때 사용자가 어떤게 문제인지를 잘 알 수 있겠네요

2024-05-05 14:06 UTC, cacaocoffee approved these changes
4주차 과제하느라 수고하셨습니다!

2024-05-05 14:06 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/model/info/ResponseGetInfoDto.kt
> +)
UserInfo가 ResponseGetInfoDto 에서만 사용되는  data class 라면 { }  로 묶어주면 좋을거 같아요

2024-05-05 14:06 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/utils/NetworkUtil.kt
> +}
우와... 이런방법이 있군요! 배워가요

2024-05-05 14:06 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/presentation/auth/login/LoginViewModel.kt
> +                    _status.postValue(true)
postvalue라는걸 몰랐는데 덕분에 배우고 가요

2024-05-05 15:11 UTC, chanubc commented on app/src/main/java/com/sopt/now/presentation/auth/login/LoginViewModel.kt
> +                    _status.postValue(true)
음 근데 retrofit과 suspend와 Resopnse를 통해 비동기적으로 네트워크 작업을 수행하고 그 결과를 ui반영하는 거라..
여기서는
```kotlin
_status.value = true
```
가 더 맞을 수 도 있다는 생각이 드네요

2024-05-05 16:14 UTC, chanubc commented on app/src/main/java/com/sopt/now/presentation/auth/login/LoginViewModel.kt
> +                    _status.postValue(true)
setValue : 메인스레드에서 작동, 
postValue : 백그라운드 스레드에서 작동, 예를 들어 사용자가 로그인 버튼을 여러번 동시에 우다다 누르게 되면 마지막에 누른 postValue() 값만 감지 죔. 백그라운드에서 작동하다가 메인스레드로 값을 전달.

data Binding이나 값이 변경되고 해당 값을 액티비티나 프레그먼트에 직접 get해야 하는 경우에는 반드시 setValue를 써야 함!

반대로 setValue이기 때문에 메인 스레드에서 진행되기 때문에 메인 스레드가 응답하지 않는경우 문제가 발생 할 수 있음.
따라서 setValue 가 필수로 필요한 상황이 아니고서야 postValue 를 통한 비동기로 값 세팅해주는 게 낫다
- 친구들과 토의해본 결과

결론 : 지금과 같은 구조에서는 post든 setValue든 상관없다!

2024-05-08 04:38 UTC, OliviaYJH commented on app/build.gradle
> +    kapt "com.google.dagger:hilt-compiler:2.48.1"
앗 들켰네요...😁

2024-05-08 04:38 UTC, OliviaYJH commented on app/src/main/java/com/sopt/now/model/login/ResponseLoginDto.kt
> +)
적용해보겠습니당!

2024-05-08 04:38 UTC, OliviaYJH commented on app/src/main/java/com/sopt/now/presentation/auth/login/LoginActivity.kt
> +    }
오오 scope 함수 다시 공부해야겠네요! 감사합니다!

2024-05-08 04:38 UTC, OliviaYJH commented on app/src/main/java/com/sopt/now/utils/ApiFactory.kt
> +}
오 이런 생각은 못해봤는데!! 더 생각하면서 코드 작성을 해야겠네요..ㅎㅎ

2024-05-22 06:29 UTC, merged