Feat/week xml06
NOW-SOPT-ANDROID/jeonghyun-yu pull request #15
Opened 2024-05-24 13:30 UTC by OliviaYJH

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #13 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- viewModel 사용하여 서버통신 로직을 UI 로직과 적절하게 분리하기
- LiveData를 활용하여 반응형 프로그래밍 패러다임 적용해보기
 

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/NOW-SOPT-ANDROID/jeonghyun-yu/assets/81751105/40e99008-0850-424a-8695-ac8af975fb2a

2024-05-26 14:50 UTC, hyoeunjoo reviewed
합세부터 6주차 과제까지 너무 고생 많으셨습니다!!
우리 볼 날이 얼마 안남았네요ㅜㅠ 안돼애~

2024-05-26 14:50 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/presentation/auth/signup/SignupActivity.kt
> +                    backToLogin()
<*>는 처음 봐요..!
제네릭 타입을 표현하는데 사용하는 문법이라고 하는군요..!!

2024-05-26 14:50 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/utils/UiState.kt
> +}
므찌다...

2024-05-26 15:30 UTC, cacaocoffee approved these changes
수고하셨습니다!
합세하느라 바쁘셨을텐데 고생하셨어요! 저도 다음에 stateflow로 변경해봐야겠어요

2024-05-26 15:30 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/presentation/auth/signup/SignupActivity.kt
> +                    backToLogin()
저도 이렇게 쓰는건 처음봤어요 신기하네요!

2024-05-26 15:30 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/presentation/auth/login/LoginViewModel.kt
>          viewModelScope.launch(Dispatchers.IO) {
launch에 Dispatchers.IO 라는 디테일까지 있는걸 이제야 봤네요... 고수 그자체.. 
stateFlow 를 아직 어려워하고 있었는데 덕분에 많이 배웠어요

2024-05-26 15:30 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/presentation/auth/login/LoginViewModel.kt
> +                    )
runcatch 문에서 onsuccess 문은 runcatch 문구가 성공했을때로 알고 있어서 
onFailure 에서 넘어오는 인자가 HTTP예외인지 확인해서 에러 메시지를 작업했는데 위와 같이도 쓸 수있나보군요

2024-06-03 23:08 UTC, chanubc approved these changes
고생하셨어요!! 항상 잘하시네요..ㅎㅎ

2024-06-03 23:08 UTC, chanubc commented on app/src/main/java/com/sopt/now/presentation/auth/login/LoginActivity.kt
> +                is UiState.SUCCESS<*> -> {
```suggestion
                is UiState.LOADING -> Unit
                is UiState.SUCCESS -> {
```
이렇게도 사용가능합니다!

추가로 state 와 flow를 생명주기를 고려하여 onEach로  정확하게 하셨네요!

2024-06-03 23:08 UTC, chanubc commented on app/src/main/java/com/sopt/now/presentation/auth/signup/SignUpViewModel.kt
> +    val state = _state.asStateFlow()
## StateFlow vs SharedFlow
### 부제 :  state vs event

**stateFlow의  경우 state에 적합합니다!**
여기서 state란 신규 구독 이후 발생한 최신 값을 말합니다! 정의하신 uistate에서는 **로딩,성공,실패** 3가지가 있겠네요!

stateflow로 하게 되면 다중 유저 혹은 다양한 Failure을 받을 수 있는 로그인, 회원가입 의 경우 다양한 유저 id혹은 password로 로그인 시도, 그리고 실패시에 state가 **항상 최초 failure** 로 유지 되게 됩니다.

한번 Failure가 발생할 경우에 다시 failure을 방출하게 된다면 stateflow는 같은 failure값을 collect하지 않고 **skip**하게 됩니다. 따라서 state의 변경이 되지 않는 셈이죠

우리의 api의 경우 로그인 실패시에 다양한 에러 메세지를 송출합니다. 다양한 유저 아이디 혹은 비밀 번호로 로그인 할때마다 (초 failufe 이후), 즉 값을 중복으로 방출할 경우 **collect 하지 않고 skip**이 될 우려가 있습니다!

즉 유저가 버튼을 여러번 눌렀을때 발생하는 event에 대해서 변화 감지가 불가능 한거죠!

한번 여러가지 id 비밀 번호로 로그인을 해보면 감이 올겁니다!! 예를들어 id오류에서 한번 failure가 발생한 경우 id를 알맞게 수정한 후 password를 틀리게 한 후 다시 버튼을 누를시에 최초 발생한 failure인 id오류가 동일하게 송출 될겁니다

**반면 sharedFlow의 경우**
collect를 한 시점 부터 발행된 모든 데이터를 받게 됩니다! 즉 failure가 중복 발행 되더라도 모두 발행을 해주기 때문에 이러한 버튼을 누르는 event와 더불어 다양한 실패 상황에 사용하기 적합 합니다!

즉 회원가입,로그인과 같이 상태 뿐만 이 아닌 특정 상황에 대하여 구독자들에게 이벤트가 발생함 전달하기에는 sharedFlow가 더 적합하다 생각합니다.

물론 stateFlow로 하고 각 오류 상황(id오류, pwd오류) 을 분리하여 상태로 만든다면 stateFlow를 사용하는게 더 효과적일 수 있습니다!!

이건 프로젝트 상황 및 개인의 선호도에 따라 작성하시면 될것 같아요

링크 첨부합니다!
https://developer88.tistory.com/entry/StateFlow-vs-SharedFlow-%EB%A5%BC-%EB%B9%84%EA%B5%90%ED%95%B4%EB%B3%B4%EC%9E%90-%EC%9D%B4%EB%B2%A4%ED%8A%B8-%ED%95%B8%EB%93%A4%EB%A7%81

https://velog.io/@vov3616/StateFlow-vs-SharedFlow%EC%9D%98-%EC%B0%A8%EC%9D%B4%EC%A0%90-%EC%95%8C%EA%B3%A0%EC%9E%88%EB%8B%88

2024-06-03 23:08 UTC, chanubc commented on app/src/main/java/com/sopt/now/presentation/auth/signup/SignupActivity.kt
> +                    backToLogin()
<*> 생략해도 됩니다!

2024-06-03 23:08 UTC, chanubc commented on app/src/main/java/com/sopt/now/presentation/main/mypage/MyPageFragment.kt
> +                is UiState.SUCCESS<*> -> { showUserInfo(state.data as UserInfo) }
제너릭 타입을 사용하면서 타입 캐스팅이 필요한 것으로 보여요!
해당 타입의 경우 코틀린의 최상위 타입인 Any? 를 반환하기 때문에 타입 캐스팅이 필요 할 겁니다
```suggestion
                is UiState.SUCCESS ->  showUserInfo(state.data)
```
이런식으로도 사용 가능합니다! 첫번째 코드에서는 안전하지 않은 타입 캐스팅 이기 때문에
ClassCastException이 발생할 가능성이 있습니다!

2024-06-03 23:10 UTC, chanubc requested changes
stateFlow와 타입캐스팅 부분은 수정해주세요!

2024-06-06 03:16 UTC, OliviaYJH commented on app/src/main/java/com/sopt/now/presentation/auth/signup/SignupActivity.kt
> +                    backToLogin()
생략해서 쓰려고 했는데 에러가 나더라구요...

2024-06-06 03:19 UTC, OliviaYJH commented on app/src/main/java/com/sopt/now/presentation/main/mypage/MyPageFragment.kt
> +                is UiState.SUCCESS<*> -> { showUserInfo(state.data as UserInfo) }
![image](https://github.com/NOW-SOPT-ANDROID/jeonghyun-yu/assets/81751105/f704581f-ce76-4a1f-8981-8218a3e35ceb)

저도 제네릭 타입 작성 피하려고 했는데 이렇게 수정해도 컴파일에서 오류가 나네여..

2024-06-06 04:12 UTC, hyoeunjoo approved these changes

2024-06-06 07:15 UTC, chanubc approved these changes

2024-06-06 07:21 UTC, chanubc commented on app/src/main/java/com/sopt/now/presentation/auth/signup/SignupActivity.kt
> +                is UiState.FAILURE -> { showToast(state.errorMessage) }
여기도 launchIn 붙여주세요!!

2024-06-06 07:24 UTC, chanubc commented on app/src/main/java/com/sopt/now/presentation/main/mypage/MyPageFragment.kt
> +                is UiState.SUCCESS<*> -> { showUserInfo(state.data as UserInfo) }
이거 마이페이지 뷰모델에서 Uistate의 타입을 지정해주어야해요!

2024-06-06 07:41 UTC, chanubc commented on app/src/main/java/com/sopt/now/presentation/main/mypage/MyPageFragment.kt
> +                is UiState.SUCCESS<*> -> { showUserInfo(state.data as UserInfo) }
우선 util로 선언된 ui state 자체가 제너릭 타입을 사용하여 uiState 에 타입 안정성을 제공해 줍니다! 

```kotlin
sealed class UiState<out T> {
    data object LOADING : UiState<Nothing>()
    data class SUCCESS<T>(
        val data: T? = null,
    ) : UiState<T>()

    data class FAILURE(
        val errorMessage: String,
    ) : UiState<Nothing>()
}
```

다음 MyPageViewModel의 staeflow변수 초기화에 UserInfo타입을 넣어줍니다
```kotlin
    private val _state = MutableStateFlow<UiState<UserInfo>>(UiState.LOADING)
    val state get() = _state.asStateFlow()
```

마지막으로 액티비티에서 flow를 수집해줍니다!
```kotlin
    private fun observeUserInfo() {
        myPageViewModel.state.flowWithLifecycle(lifecycle).onEach { state ->
            when (state) {
                is UiState.LOADING -> {}
                is UiState.SUCCESS -> {
                    state.data?.let { showUserInfo(it) }
                }
                is UiState.FAILURE -> { requireContext().showToast(state.errorMessage) }
            }
        }.launchIn(lifecycleScope)
    }
```

일반적으로 UIstate는 이렇게 사용해요! Uistate의 제너릭 타입을 받아야 타입 안정성이 확보되고 Success시에 어떠한 타입의 데이터를 전달하는지 확실하게 알 수 있어서요!

2024-06-06 07:43 UTC, chanubc commented on app/src/main/java/com/sopt/now/presentation/main/mypage/MyPageFragment.kt
> +                is UiState.SUCCESS<*> -> { showUserInfo(state.data as UserInfo) }
Success시에 데이터를 가져가야하는 마이페이지 뷰모델을 제외하고는 나머진 기존 제너릭타입으로 타입 캐스팅을 해도 무방할것 같긴합니다!

2024-06-07 00:27 UTC, OliviaYJH commented on app/src/main/java/com/sopt/now/presentation/main/mypage/MyPageFragment.kt
> +                is UiState.SUCCESS<*> -> { showUserInfo(state.data as UserInfo) }
아하!! 자세한 설명 감사합니다! 적용해볼게요!!

2024-06-07 00:32 UTC, merged