Feat/week xml02
NOW-SOPT-ANDROID/jeonghyun-yu pull request #7
Opened 2024-04-18 01:38 UTC by OliviaYJH

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #5 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
-  바텀 네비게이션 연결
- 프로필 리스트 구성
- 데이터 스크롤 시 내 프로필도 함께 스크롤

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/NOW-SOPT-ANDROID/jeonghyun-yu/assets/81751105/1391a380-f98c-42d7-819d-120415f0608c

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴

2024-04-21 11:44 UTC, chanubc requested changes
어려웠을텐데 고생 많으셨습니다! 코드를 정말 가독성 있게 잘 작성하시는 것 같습니다.

수정사항은 반영해주세요!

2024-04-21 11:44 UTC, chanubc commented on app/src/main/java/com/sopt/now/presentation/main/home/ProfileAdapter.kt
> +    }
지금 R을 활용하여 전체적으로 반복 되는 코드들이 많습니다!

viewtype을 resource로 직접 판단하는 방법도 좋지만

```kotlin
companion object {
        private const val VIEW_TYPE_MY_PROFILE = 0
        private const val VIEW_TYPE_FRIEND_PROFILE = 1
        private const val VIEW_TYPE_FRIEND_PROFILE_WITH_MUSIC = 2
    }
```
이런식으로 상수화 하게 되면 resource로 비교하는게 아닌 상수화 된 숫자로 비교하게 되어 불필요한 R 사용을 방지하고 유지보수에 좀 더 좋겠네요!

2024-04-21 11:44 UTC, chanubc commented on app/src/main/java/com/sopt/now/presentation/main/mypage/MyPageFragment.kt
> +    }
해당 메서드가 view를 항상 반환하기 때문에 View뒤에 null타입 체크 "?"는 지워주세요!

2024-04-21 11:44 UTC, chanubc commented on app/src/main/java/com/sopt/now/presentation/main/mypage/MyPageFragment.kt
> +    }
not null

2024-04-21 11:44 UTC, chanubc commented on app/src/main/java/com/sopt/now/presentation/main/mypage/MyPageFragment.kt
> +    }
시간되시면 확장함수로 따로 만들어 보셔도 좋습니다!

2024-04-21 11:44 UTC, chanubc commented on app/src/main/res/drawable/img_jeonghyun.jpeg
아이컨택 햇어요

2024-04-21 11:44 UTC, chanubc commented on app/src/main/res/drawable/img_profile_2.jpeg
얘가 누구라구요>?

2024-04-21 11:44 UTC, chanubc commented on app/src/main/res/drawable/rect_green_radius_15.xml
> +        android:color="#4CAF50"
얘도 color.xml에 값 빼주시면 조아요

2024-04-21 11:44 UTC, chanubc commented on app/src/main/res/layout/fragment_home.xml
> +        android:layout_height="match_parent"
constraint 에서는 0dp 사용을 지향합시다!

2024-04-21 11:44 UTC, chanubc commented on app/src/main/res/layout/item_my_friends_with_music.xml
> +
이부분에서 Linear를 따로 중첩시키신 이유가 있을까요?
constraint로도 충분 할 것 같아서요!

2024-04-21 11:44 UTC, chanubc commented on app/src/main/java/com/sopt/now/presentation/main/search/SearchFragment.kt
> +    ): View? {
얘도 지워주세요!

2024-04-21 11:44 UTC, chanubc commented on app/src/main/java/com/sopt/now/presentation/main/home/ProfileAdapter.kt
> +        notifyDataSetChanged()
notifyDataSetChanged() 
방금 보았던 **notifyDataSetChanged() 는 structural changes 에 해당**하며, **보이는 모든 View 에 대해서 재배치와 재구성을 진행**하게 됩니다.

예를들어 하나의 아이템의 +버튼을 누르고 숫자 0을 1로 업데이트 하려는 프로젝트 가 있습니다. 이벤트가 발생할때 마다 notifyDataSetChanged() 로 UI 를 업데이트하는 것은 "0" 이라는 텍스트를 "1" 로 변경하고 싶을 뿐인데, 전체 item 을 재배치하고 재구성하게 되는 것이기에 비효율적입니다.

이러한 점 때문에 **공식문서에서는 notifyDataSetChanged() 는 최후의 수단으로 활용하고, 일반적으로는 구체적인 이벤트를 사용하여 item changes 가 실행되도록 구현하는 것이 더욱 효율적**이라고 안내하고 있습니다.

listadpater와 diffutil이 뭔지 공부해보시면 좋겠습니다!

2024-04-21 12:30 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/model/Profile.kt
> +
엇 블로그 스터디에서 봤던 내용이네요ㅎㅎ

2024-04-21 12:35 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/presentation/main/home/ProfileAdapter.kt
> +    }
가독성 미쳤네요

2024-04-21 12:39 UTC, hyoeunjoo approved these changes
배울게 정말 많아요.. 시험 끝나면 다시 보면서 적용해볼게 많네요 ㅎㅎ 
수고 많으셨어요~!!

2024-04-21 12:39 UTC, hyoeunjoo commented on app/src/main/java/com/sopt/now/presentation/main/mypage/MyPageFragment.kt
> +
오우... @RequiresApi이 무엇인지 한 번 알아봐야겠습니다
메모해놓고 가용 ㅎ

2024-04-21 12:39 UTC, hyoeunjoo commented on app/src/main/res/drawable/img_jeonghyun.jpeg
> 아이컨택 햇어요

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-04-21 12:39 UTC, hyoeunjoo commented on app/src/main/res/drawable/img_jeonghyun.jpeg
이뿌다아!!!!!ㅎㅎㅎ

2024-04-21 13:23 UTC, cacaocoffee approved these changes
2주차 수고했어!

2024-04-21 13:23 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/presentation/main/MainActivity.kt
> +    @RequiresApi(Build.VERSION_CODES.TIRAMISU)
onCreate부분에   @RequiresApi(Build.VERSION_CODES.TIRAMISU)은 어디에 필요한건가요?

2024-04-21 13:23 UTC, cacaocoffee commented on app/src/main/java/com/sopt/now/presentation/main/home/HomeFragment.kt
> +}
여백이 없으면 더 좋을거같아요:D

2024-04-21 13:23 UTC, cacaocoffee commented on app/src/main/res/drawable/img_jeonghyun.jpeg
또 놀랬다..

2024-04-21 13:23 UTC, cacaocoffee commented on app/src/main/res/drawable/img_profile_2.jpeg
옴팡이?

2024-04-29 13:13 UTC, chanubc approved these changes

2024-04-29 16:04 UTC, OliviaYJH commented on app/src/main/res/drawable/img_profile_2.jpeg
맞아요 옴팡이!!

2024-04-29 16:07 UTC, OliviaYJH commented on app/src/main/res/layout/item_my_friends_with_music.xml
> +
Constraint로 하면 일일이 체인을 형성시켜줘야 해서 linear로 했습니다!

2024-04-29 16:09 UTC, OliviaYJH commented on app/src/main/java/com/sopt/now/presentation/main/MainActivity.kt
> +    @RequiresApi(Build.VERSION_CODES.TIRAMISU)
getUserInfo 메서드에서 빌드 버전에 따라 분기처리를 하도록 했어요. 
그런데 이 메서드를 onCreate에서 호출하려고 하니 여기에서도 어노테이션을 작성해야한다고 하더라고요

2024-04-29 16:14 UTC, merged